services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: chatbot_db
      POSTGRES_USER: chatbot
      POSTGRES_PASSWORD: chatbot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d chatbot_fact_checker"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s

  minio:
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z
    container_name: local-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  minio_init:
    image: minio/mc:RELEASE.2024-11-05T11-29-45Z
    container_name: local-minio-init
    depends_on:
      - minio
    environment:
      MC_HOST_local: http://minioadmin:minioadmin@minio:9000
    entrypoint:
      - /bin/sh
      - -c
      - |
        set -eux

        echo "Waiting for MinIO to be reachable..."
        until mc ls local >/dev/null 2>&1; do
          sleep 1
        done

        mc mb --ignore-existing local/chatbot-bucket
        echo "MinIO bucket ensured: chatbot-bucket"
        mc ls local
    restart: "no"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  ollama:
    image: ollama/ollama:latest
    environment:
      OLLAMA_MODEL: "smollm2:135m-instruct-q4_1"
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    entrypoint: ["/bin/sh"]
    command:
      - "-c"
      - "ollama serve & sleep 2; ollama pull smollm2:135m-instruct-q4_1; wait"
        

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    environment:
      OLLAMA_MODEL: "smollm2:135m-instruct-q4_1"
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - ollama
      - postgres
      - minio

  frontend:
    build:
      context: ./frontend
    environment:
      BACKEND_PROXY_TARGET: "http://backend:8000"
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  ollama:    
  postgres_data:
  minio_data:
