"""0001_create_uploaded_files

Revision ID: 179e8c7c3c1b
Revises: 
Create Date: 2026-01-10 19:04:29.907172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '179e8c7c3c1b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('file_id', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=128), nullable=False),
    sa.Column('stored_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.CheckConstraint("source IN ('uploaded', 'system')", name='ck_uploaded_files_source_allowed'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash', name='uq_uploaded_files_file_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploaded_files')
    # ### end Alembic commands ###
